version: "2"
services:
  app:
    build: ./app
    container_name: "Flask_App_Final"
    links:
      - db
    depends_on:
      - db
    ports:
      - "5000:5000"

  app3:
    build: ./app3
    container_name: "Flask_App_Part3"
    ports:
      - "5003:5003"

  db:
    image: mysql:5.7
    container_name: "MySQL_Database_Final"
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro